# Generated by Django 4.0.4 on 2022-05-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='owner',
            new_name='user',
        ),
    ]
