# Generated by Django 4.0.4 on 2022-05-12 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'code enter must be uppercase letters & numbers')]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_coupen',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discounttype',
            field=models.CharField(choices=[('flat', 'Flat'), ('Percentage', 'percentage')], default='Flat', max_length=10),
        ),
    ]
