# Generated by Django 4.0.4 on 2022-05-13 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_rename_coupon_order_code_rename_owner_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=None, help_text='enter discount under 100', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
