# Generated by Django 4.0.4 on 2022-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_alter_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_coupon',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
