# Generated by Django 4.0.4 on 2022-05-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_rename_discounttype_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Percentage', 'Percentage')], default='Flat', max_length=10),
        ),
    ]
